/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_25 (coord M15), LPUART1_RXD */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_RXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_RXD_SIGNAL                                    RXD   /*!< Signal name */

/* GPIO_AD_24 (coord L13), LPUART1_TXD */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_TXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_TXD_SIGNAL                                    TXD   /*!< Signal name */

/* GPIO_SNVS_00 (coord R10), J42[3] */
/* Routed pin properties */
#define BOARD_INITPINS_Test_R10_PERIPHERAL                                GPIO13   /*!< Peripheral name */
#define BOARD_INITPINS_Test_R10_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_Test_R10_CHANNEL                                       3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Test_R10_GPIO                                      GPIO13   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_Test_R10_GPIO_PIN                                      3U   /*!< GPIO pin number */
#define BOARD_INITPINS_Test_R10_GPIO_PIN_MASK                         (1U << 3U)   /*!< GPIO pin mask */

/* GPIO_SNVS_01 (coord P10), J42[4] */
/* Routed pin properties */
#define BOARD_INITPINS_Test_P10_PERIPHERAL                                GPIO13   /*!< Peripheral name */
#define BOARD_INITPINS_Test_P10_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_Test_P10_CHANNEL                                       4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Test_P10_GPIO                                      GPIO13   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_Test_P10_GPIO_PIN                                      4U   /*!< GPIO pin number */
#define BOARD_INITPINS_Test_P10_GPIO_PIN_MASK                         (1U << 4U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
