/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_06 (number 52), LPSPI1_SCK/INT2_COMBO/J56[8]/J57[12]/U26[9]/U27[6] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_SCK_PERIPHERAL                                PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_SCK_SIGNAL                                       A   /*!< Signal name */
#define BOARD_INITPINS_LPSPI1_SCK_CHANNEL                                     3U   /*!< Signal channel */

/* GPIO_01 (number 12), I2C1_SDA/U10[18]/J57[18]/U26[6] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C1_SDA_PERIPHERAL                                LPI2C1   /*!< Peripheral name */
#define BOARD_INITPINS_I2C1_SDA_SIGNAL                                       SDA   /*!< Signal name */

/* GPIO_02 (number 11), I2C1_SCL/U10[17]/J57[20]/U26[4] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C1_SCL_PERIPHERAL                                LPI2C1   /*!< Peripheral name */
#define BOARD_INITPINS_I2C1_SCL_SIGNAL                                       SCL   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
